# Generated by Django 5.0.12 on 2025-03-30 02:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Athletes",
            fields=[
                (
                    "athleteid",
                    models.AutoField(
                        db_column="AthleteID", primary_key=True, serialize=False
                    ),
                ),
                (
                    "fullname",
                    models.CharField(
                        blank=True,
                        db_collation="Cyrillic_General_CI_AS",
                        db_column="FullName",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "dateofbirth",
                    models.DateField(blank=True, db_column="DateOfBirth", null=True),
                ),
                (
                    "weight",
                    models.IntegerField(blank=True, db_column="Weight", null=True),
                ),
                (
                    "height",
                    models.IntegerField(blank=True, db_column="Height", null=True),
                ),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        db_collation="Cyrillic_General_CI_AS",
                        db_column="Gender",
                        max_length=10,
                        null=True,
                    ),
                ),
            ],
            options={
                "db_table": "Athletes",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Coaches",
            fields=[
                (
                    "coachid",
                    models.AutoField(
                        db_column="CoachID", primary_key=True, serialize=False
                    ),
                ),
                (
                    "fullname",
                    models.CharField(
                        blank=True,
                        db_collation="Cyrillic_General_CI_AS",
                        db_column="FullName",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "dateofbirth",
                    models.DateField(blank=True, db_column="DateOfBirth", null=True),
                ),
            ],
            options={
                "db_table": "Coaches",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Games",
            fields=[
                (
                    "gameid",
                    models.AutoField(
                        db_column="GameID", primary_key=True, serialize=False
                    ),
                ),
                ("date", models.DateField(blank=True, db_column="Date", null=True)),
                (
                    "location",
                    models.CharField(
                        blank=True,
                        db_collation="Cyrillic_General_CI_AS",
                        db_column="Location",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "score",
                    models.CharField(
                        blank=True,
                        db_collation="Cyrillic_General_CI_AS",
                        db_column="Score",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "hierarchy",
                    models.IntegerField(blank=True, db_column="Hierarchy", null=True),
                ),
            ],
            options={
                "db_table": "Games",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Tournaments",
            fields=[
                (
                    "tournamentid",
                    models.AutoField(
                        db_column="TournamentID", primary_key=True, serialize=False
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        db_collation="Cyrillic_General_CI_AS",
                        db_column="Name",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True,
                        db_collation="Cyrillic_General_CI_AS",
                        db_column="Location",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "startdate",
                    models.DateField(blank=True, db_column="StartDate", null=True),
                ),
                (
                    "enddate",
                    models.DateField(blank=True, db_column="EndDate", null=True),
                ),
                (
                    "rating",
                    models.IntegerField(blank=True, db_column="Rating", null=True),
                ),
            ],
            options={
                "db_table": "Tournaments",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Attendance",
            fields=[
                (
                    "attendanceid",
                    models.AutoField(
                        db_column="AttendanceID", primary_key=True, serialize=False
                    ),
                ),
                (
                    "pressrating",
                    models.IntegerField(blank=True, db_column="PressRating", null=True),
                ),
                (
                    "captainrating",
                    models.IntegerField(
                        blank=True, db_column="CaptainRating", null=True
                    ),
                ),
                (
                    "coachrating",
                    models.IntegerField(blank=True, db_column="CoachRating", null=True),
                ),
                (
                    "athleteid",
                    models.ForeignKey(
                        blank=True,
                        db_column="AthleteID",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="football.athletes",
                    ),
                ),
            ],
            options={
                "db_table": "Attendance",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Results",
            fields=[
                (
                    "resultid",
                    models.AutoField(
                        db_column="ResultID", primary_key=True, serialize=False
                    ),
                ),
                (
                    "athleteplace",
                    models.IntegerField(
                        blank=True, db_column="AthletePlace", null=True
                    ),
                ),
                (
                    "goalsscored",
                    models.IntegerField(blank=True, db_column="GoalsScored", null=True),
                ),
                (
                    "athleteid",
                    models.ForeignKey(
                        blank=True,
                        db_column="AthleteID",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="football.athletes",
                    ),
                ),
            ],
            options={
                "db_table": "Results",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Teams",
            fields=[
                (
                    "teamid",
                    models.AutoField(
                        db_column="TeamID", primary_key=True, serialize=False
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        db_collation="Cyrillic_General_CI_AS",
                        db_column="Name",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "rating",
                    models.IntegerField(blank=True, db_column="Rating", null=True),
                ),
                ("wins", models.IntegerField(blank=True, db_column="Wins", null=True)),
                (
                    "losses",
                    models.IntegerField(blank=True, db_column="Losses", null=True),
                ),
                (
                    "draws",
                    models.IntegerField(blank=True, db_column="Draws", null=True),
                ),
                (
                    "coachid",
                    models.ForeignKey(
                        blank=True,
                        db_column="CoachID",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="football.coaches",
                    ),
                ),
            ],
            options={
                "db_table": "Teams",
                "managed": True,
            },
        ),
        migrations.AddField(
            model_name="athletes",
            name="teamid",
            field=models.ForeignKey(
                blank=True,
                db_column="TeamID",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="football.teams",
            ),
        ),
        migrations.CreateModel(
            name="Teamsingames",
            fields=[
                (
                    "teamsingameid",
                    models.AutoField(
                        db_column="TeamsingamesID", primary_key=True, serialize=False
                    ),
                ),
                (
                    "gameid",
                    models.ForeignKey(
                        db_column="GameID",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="football.games",
                    ),
                ),
                (
                    "teamid",
                    models.ForeignKey(
                        db_column="TeamID",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="football.teams",
                    ),
                ),
            ],
            options={
                "db_table": "TeamsInGames",
                "managed": True,
            },
        ),
        migrations.AddField(
            model_name="games",
            name="tournamentid",
            field=models.ForeignKey(
                blank=True,
                db_column="TournamentID",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="football.tournaments",
            ),
        ),
        migrations.CreateModel(
            name="Applications",
            fields=[
                (
                    "applicationid",
                    models.AutoField(
                        db_column="ApplicationID", primary_key=True, serialize=False
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        db_collation="Cyrillic_General_CI_AS",
                        db_column="Status",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "tournamentid",
                    models.ForeignKey(
                        blank=True,
                        db_column="TournamentID",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="football.tournaments",
                    ),
                ),
            ],
            options={
                "db_table": "Applications",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Trainings",
            fields=[
                (
                    "trainingid",
                    models.AutoField(
                        db_column="TrainingID", primary_key=True, serialize=False
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        db_collation="Cyrillic_General_CI_AS",
                        db_column="Name",
                        max_length=255,
                        null=True,
                    ),
                ),
                ("date", models.DateField(blank=True, db_column="Date", null=True)),
                (
                    "teamid",
                    models.ForeignKey(
                        blank=True,
                        db_column="TeamID",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="football.teams",
                    ),
                ),
            ],
            options={
                "db_table": "Trainings",
                "managed": True,
            },
        ),
    ]
